
        instr 1
; list of min and max for the mappable parameters
   chnset 0, "inlevel_min" 
   chnset 1.0, "inlevel_max" 
   chnset 0, "mincertime_min" 
   chnset 0.99, "mincertime_max" 
   chnset 0.0, "mincerpitch_min" 
   chnset 2.0, "mincerpitch_max" 
   chnset 0.0, "mincerfeed_min" 
   chnset 1.0, "mincerfeed_max" 
   chnset 0, "mincermix_min" 
   chnset 1.0, "mincermix_max" 
   chnset 0.0, "Pan_min" 
   chnset 1.0, "Pan_max" 
   chnset 0.0, "reverbtime_min" 
   chnset 8.0, "reverbtime_max" 
   chnset 0.0, "reverbdamp_min" 
   chnset 1.0, "reverbdamp_max" 
   chnset 0.0, "reverbmix_min" 
   chnset 1.0, "reverbmix_max" 
                        
        endin
