
        instr 1
; list of min and max for the mappable parameters
   chnset 0.0, "Feed_min" 
   chnset 1.0, "Feed_max" 
   chnset 100, "FiltFq_min" 
   chnset 14000, "FiltFq_max" 
   chnset 0.0, "PitchMod_min" 
   chnset 4.0, "PitchMod_max" 
   chnset 0.0, "PreDly_min" 
   chnset 500, "PreDly_max" 
   chnset 20, "LfRoll_min" 
   chnset 500, "LfRoll_max" 
   chnset 0.0, "Mix_min" 
   chnset 1.0, "Mix_max" 
                        
        endin
